language: node_js
node_js:
- '0.12'
- '4'
- '5'
- '6'
env:
  global:
    - KEYSTONE_PREBUILD_ADMIN=true
matrix:
  include:
    node_js: '6'
    addons:
      sauce_connect: true
    script:
      - npm run test-e2e-saucelabs
before_script:
- npm run lint
- sleep 15
script:
- npm run test-cov
- npm run test-admin
sudo: required
notifications:
  email:
  - jed@keystonejs.com
  slack:
    secure: AqayzYjoHTlwE85pgB0h5yqpyBDWbdrpiXKXhb8tSqWPKi6unhkfZ4r11kQRowoDQXb+fue9367u+lJ9lKBfMv+SSFnKY+OccasfrW6JwJ8Wi258aB7bjcSP9kUtUfvbbvPSwQjY6Z8+9TlMxP6kyabeZ69SGnhnaJNt+vbAJzc=
services:
- mongodb
git:
  depth: 10
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
