language: node_js
node_js:
- '0.12'
- '4'
- '5'
- '6'
env:
  global:
    - KEYSTONE_PREBUILD_ADMIN=true
  matrix:
    - JOB=unit_tests
matrix:
  include:
    - node_js: '6'
      script:
        - npm run test-cov
      env:
        - JOB=test-cov
    - node_js: '6'
      script:
        - npm run lint
      env:
        - JOB=lint
    - node_js: '6'
      addons:
        sauce_connect: true
      script:
        - npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group001Login
    - node_js: '6'
      addons:
        sauce_connect: true
      script:
        - npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group002Home
    - node_js: '6'
      addons:
        sauce_connect: true
      script:
        - npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group003List
    - node_js: '6'
      addons:
        sauce_connect: true
      script:
        - npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group004Item
    - node_js: '6'
      addons:
        sauce_connect: true
      script:
        - npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group005Fields
before_script:
- sleep 15
script:
- npm run test-admin
sudo: required
notifications:
  email:
  - jed@keystonejs.com
  slack:
    secure: AqayzYjoHTlwE85pgB0h5yqpyBDWbdrpiXKXhb8tSqWPKi6unhkfZ4r11kQRowoDQXb+fue9367u+lJ9lKBfMv+SSFnKY+OccasfrW6JwJ8Wi258aB7bjcSP9kUtUfvbbvPSwQjY6Z8+9TlMxP6kyabeZ69SGnhnaJNt+vbAJzc=
services:
- mongodb
git:
  depth: 10
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
