language: node_js
node_js:
  - "0.12"

before_script:
  - npm run lint
  - sleep 15

script:
  - npm run test-cov
  - npm run test-e2e-saucelabs

sudo: required

notifications:
  email:
    - jed@keystonejs.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
  sauce_connect: true
